name: Build Python App for Linux (x86_64)

on:
  workflow_dispatch:  # Only allow manual run

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu as the build environment

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4  # Checks out the repository code

    # Step 2: Use Docker to simulate a low version glibc environment
    - name: Build executable with Docker (Ubuntu 18.04)
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace ubuntu:18.04 bash -c "
          apt-get update && apt-get install -y software-properties-common  # Install required tools
          add-apt-repository ppa:deadsnakes/ppa  # Add the PPA for more Python versions
          apt-get update && apt-get install -y python3.12 python3.12-distutils python3.12-venv  # Install Python 3.12 and associated packages
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12  # Install pip for Python 3.12
          pip3 install --upgrade pip  # Upgrade pip to avoid issues with old versions
          pip3 install -r requirements.txt  # Install dependencies from requirements.txt
          pip3 install pyinstaller  # Install PyInstaller
          pyinstaller --onefile demo.py  # Build the executable with PyInstaller
        "

    # Step 3: Upload the generated executable as an artifact
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4  # Uploads the generated executable file as a GitHub Actions artifact
      with:
        name: demo-executable  # Name the artifact
        path: dist/demo  # Path to the generated executable file in the dist folder
